### ISSUE TITLE
Reduce space between the FabSpeedDial items

### ISSUE THREAD

**Issue by umarF** [kobakei/MaterialFabSpeedDial#12]
I need to reduce the space between the FabSpeedDial items, so that I can accommodate more items. How can that be done ?

**Comment by kobakei** [comment]
Sorry, this feature is not supported now.

The current margin between items is default margin of FAB with `app:useCompatPadding="true"`.
To reduce margin between items, setting negative margin in this code may work.
https://github.com/kobakei/MaterialFabSpeedDial/blob/master/library/src/main/java/io/github/kobakei/materialfabspeeddial/FabSpeedDial.java#L293-L294

**Comment by umarF** [comment]
Ok, let me try this.

**Comment by kobakei** [comment]
I added `fab_extraMargin` attribute from 1.1.6.
Please set negative value to it.

**Comment by umarF** [comment]
Awesome !
Its working great now.
Thanks.

**Comment by JoelNieman** [comment]
How do you get this to work? I'm using 1.1.7 and getting no response from the UI no matter what I set as the fab_extraMargin.





<FrameLayout                                               
    android:layout_width="match_parent"                    
    android:layout_height="match_parent"                   
    >                                                      
                                                           
    <com.sportsmantracker.app.views.SpeedDial              
        android:id="@+id/speed_dial"                       
        android:layout_width="wrap_content"                
        android:layout_height="wrap_content"               
        android:layout_gravity="end|bottom"                
        app:fab_menu="@menu/menu_map_speed_dial"           
        app:fab_miniFabBackgroundColor="@color/white_smt"  
        app:fab_miniFabTextColor="@color/white_smt"        
        app:fab_extraMargin = "-10dp"/>                    
</FrameLayout>

**Comment by JoelNieman** [comment]
Fixed it. Thanks
