### ISSUE TITLE
missing default constructor

### ISSUE THREAD

**Issue by falkontre** [kobakei/MaterialFabSpeedDial#13]
# Overview

In logs there is the stack trace attached 
[stacktrace.txt](https://github.com/kobakei/MaterialFabSpeedDial/files/1271609/stacktrace.txt)
every time I use an activity containing MaterialFabSpeedDial (the issue is not blocking App):

# Environment (required for bug report)

- OS: 
- Device:
- Can reproduce on sample app: Yes/No
  - If the issue cannot be reproduced on sample app, it is better to provide snippet or project which can reproduce it.

# Steps to reproduce (required for bug report)

-

# Expected behavior (required for bug report)

-

# Screenshot

-

**Comment by kobakei** [comment]
@falkontre 
Do you enable proguard? If so, please add the following rule to your proguard file.
```
-keep public class * extends android.support.design.widget.CoordinatorLayout$Behavior {
    public <init>(android.content.Context, android.util.AttributeSet);
}
```

If this doesn't work for the issue, please let me know.

**Comment by falkontre** [comment]
This error happens in DEBUG mode too (proguard is not enabled in dev flavour)

**Comment by kobakei** [comment]
@falkontre 
I cannot reproduce this issue with sample app.
would you tell me more detail? (Android version, device name, code or XML about the issue)

**Comment by falkontre** [comment]
Hi @kobakei 

as I stated, the error is not producing an ANR so the app will not crash, but a stacktrace is printed in log window.

Android version is: 7.1.1 running on a phisical Nexus 6 (shamu)

I grab the reference from ContentView via ButterKnife
`@BindView(R.id.fab) FabSpeedDial fab;`

and in the onCreate method I'm setting the listener in this way:
```java
fab.addOnMenuItemClickListener(new FabSpeedDial.OnMenuItemClickListener() {
	@Override
	public void onMenuItemClick(FloatingActionButton fab, TextView textView, int itemId) {
		Intent intent;
		switch (itemId) {
			case R.id.menu_supermarket:
				intent = new IntentBuilder()
					         .context(ViewShopsActivity.this)
					         .activity(SearchSupermarketActivity.class)
					         .extra("returnShopInfo", returnShopInfo)
					         .build();
				startActivityForResult(intent, REQUEST_CREATE_SHOP);
				break;
			case R.id.menu_genericShop:
				intent = new IntentBuilder()
					         .context(ViewShopsActivity.this)
					         .activity(ShopManagerActivity.class)
					         .extra("returnShopInfo", returnShopInfo)
					         .build();
				startActivityForResult(intent, REQUEST_CREATE_SHOP);
				break;
		}
	}
});
```

Anyway, maybe adding the default constructor could solve the problem?

**Comment by kobakei** [comment]
@falkontre 
I added constructor of behavior class so would you try version 1.1.7?
Please let me know whether your issue is fixed or not.
