### ISSUE TITLE
[Bug] Can't load miniFabTextBackground on Android API 16

### ISSUE THREAD

**Issue by danieldaeschle** [kobakei/MaterialFabSpeedDial#17]
# Overview

`<io.github.kobakei.materialfabspeeddial.FabSpeedDial
        android:id="@+id/recordsFab"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:fab_menu="@menu/records_fab"
        app:fab_miniFabTextBackground="@drawable/fab_label"
        app:fab_miniFabBackgroundColor="?attr/colorPrimary"
        app:fab_fabBackgroundColor="?attr/colorAccent"
        app:fab_miniFabDrawableTint="?attr/android:colorBackground"
        app:fab_fabDrawableTint="?attr/android:colorBackground" />`

# Environment (required for bug report)

- OS: Windows 10
- Device: Android Emulator Nexus 4 API 16.

# Screenshot

![image](https://user-images.githubusercontent.com/30751516/31221089-d90a9b3a-a9c2-11e7-855e-598edd9f8d0e.png)

**Comment by kobakei** [comment]
@danieldaeschle 
```
Can't convert to color: type=0x2
```
It seems that you may set wrong resource to color.

**Comment by danieldaeschle** [comment]
On API 25+ it is working
