### ISSUE TITLE
Make the library Android 15 compatible

### ISSUE THREAD

**Issue by ssuukk** [kobakei/MaterialFabSpeedDial#20]
By modyfiying:

            if (miniFabTextBackground != null) {
                Drawable.ConstantState cs = miniFabTextBackground.mutate().getConstantState();
                if (cs != null) {
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                        label.setBackground(cs.newDrawable());
                    } else {
                        label.setBackgroundDrawable(cs.newDrawable());
                    }
                }
            }
            if (miniFabTextBackgroundList != null) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                    label.setBackground(miniFabTextBackgroundList.get(index));
                } else {
                    label.setBackgroundDrawable(miniFabTextBackgroundList.get(index));
                }
            }

you allow this library to be used on android 15

**Comment by kobakei** [comment]
Thanks for your feedback.
Would you create pull request for this?

**Comment by kobakei** [comment]
Fixed at 1.1.9
