### ISSUE TITLE
Horizontal menu

### ISSUE THREAD

**Issue by alxsfrm** [kobakei/MaterialFabSpeedDial#21]
Hi Author,
is it possible to present the fab buttons menu horizontally ?

Regards,
Alex.

**Comment by kobakei** [comment]
This library can show them horizontally when device is landscape mode.
Do you mean it?

**Comment by alxsfrm** [comment]
Not exactly.
I need to present the fabs horizontally in portrait mode on cell phones.
Is it possible?


בתאריך 26 באוק׳ 2017 07:17 PM,‏ "Keisuke Kobayashi" <
notifications@github.com> כתב:

**Comment by kobakei** [comment]
Understood.
Horizontal FABs in portrait mode is not supported.
I will not support such behavior because it is not defined in material design guideline.
