### ISSUE TITLE
Anchor to BottomSheet?

### ISSUE THREAD

**Issue by 10erlosh** [kobakei/MaterialFabSpeedDial#22]
Your lib looks very promising, thank you!
One thing I miss is the ability to anchor the FSD to a BottomSheet. How can we achieve this?

**Comment by kobakei** [comment]
Sorry, FSD does not support bottom sheet now.
AFAIK, bottom sheet overlays a screen therefore FAB (or FSD) does not need to respond to it.
If you know an real example having such behavior, would you tell me?
