### ISSUE TITLE
fab_miniFabTextBackground size

### ISSUE THREAD

**Issue by okaa-pi** [kobakei/MaterialFabSpeedDial#7]
Hi.

I'm experiencing a small issue with the lib on some phones, but not all.
I'm setting the fab_miniFabTextBackground with this XML:
`<?xml version="1.0" encoding="utf-8"?>`
`<shape`
`    xmlns:android="http://schemas.android.com/apk/res/android"`
`    android:shape="rectangle">`
`    <solid android:color="?colorCardBackground" />`
`    <corners android:radius="2dp" />`
`</shape>`

Works fine on the Motorola Moto E and on the Huawei P9.

On my OnePlus 2 and Nexus 5X, some things are funky;
The first time I open the menu, everything is fine:
http://i.imgur.com/NA5waC5.png

But if I exit the menu and open it again, the background is too short?
http://i.imgur.com/q3KDus6.png

**Comment by kobakei** [comment]
Thanks for your report.
I will check this issue.

**Comment by kobakei** [comment]
@okaa-pi 
I could not reproduce this issue but I fixed similar issue about text label drawables on 1.1.2.
Would you try 1.1.2 and let me know whether this issue is fixed?

**Comment by okaa-pi** [comment]
Yep, problem solved in 1.1.2.
Thanks man =)
