### ISSUE TITLE
Square ripple on API >=21

### ISSUE THREAD

**Issue by anderscheow** [kobakei/MaterialFabSpeedDial#9]
Can you please help to remove the square ripple?

**Comment by kobakei** [comment]
@anderscheow 
Would you put code or layout XML which reproduces the issue?

**Comment by anderscheow** [comment]
i didn't do any special implementation, i just follow your guides.

**Comment by kobakei** [comment]
Do you reproduce the issue on sample app too?

**Comment by anderscheow** [comment]
Ya, it only happened on API >= 21, lower than 21 is fine

**Comment by kobakei** [comment]
I cannot reproduce it with sample app on Android 7.0 emulator therefore cannot investigate it anymore.
Please put more detail (XML, device, OS version) or you can disable ripple effect by setting no color to  `fab_fabRippleColor` and `fab_miniFabRippleColor`.

**Comment by anderscheow** [comment]
I found that it was my emulator problem, it doesn't occur on my devices, btw thanks a lot :)

**Comment by ibu2710** [comment]
This issue occurs for me in device too... 5.1 Lolipop
